"""
Industrial Inspection Report Generator
======================================
Takes the output of the Hybrid Pipeline and generates a clean,
human-readable markdown inspection report for the factory floor.

Author: Srinath
"""

import json
from pathlib import Path
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir: str = "reports/inspections"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def generate(self, pipeline_result: dict, image_path: str) -> str:
        """
        Generate a Markdown report based on pipeline output.
        
        Args:
            pipeline_result: Dict returned by HybridInspectionPipeline.inspect()
            image_path: Path to the inspected image.
            
        Returns:
            Path to the saved report file.
        """
        image_name = Path(image_path).name
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        safe_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        status = pipeline_result.get("status", "UNKNOWN")
        category = pipeline_result.get("category", "UNKNOWN")
        defect_class = pipeline_result.get("defect_classification", "None")
        conf_score = pipeline_result.get("confidence_score", 0.0)
        
        report_filename = f"Inspection_{category}_{safe_timestamp}.md"
        report_path = self.output_dir / report_filename
        
        lines = [
            f"# Industrial Inspection Report",
            f"**Date/Time:** {timestamp}",
            f"**Product Category:** {category.upper()}",
            f"**Image Name:** {image_name}",
            "",
            "---",
            ""
        ]
        
        if status == "PASS":
            lines.extend([
                "## 🟢 FINAL RESULT: PASS",
                "Product passed all quality checks. No anomalies detected.",
            ])
        elif status == "FAIL":
            lines.extend([
                "## 🔴 FINAL RESULT: FAIL",
                f"**Defect Type:** {defect_class}",
                f"**Confidence Score:** {conf_score * 100:.2f}%",
                ""
            ])
            
            yolo = pipeline_result.get("yolo")
            if yolo and yolo.get("detections"):
                lines.append("### Detected Defects (Bounding Boxes):")
                for i, det in enumerate(yolo["detections"]):
                    lines.append(f"- **Box {i+1}:** Class `{det['class']}` with {det['confidence']*100:.1f}% confidence")
                    lines.append(f"  - Coordinates: {det['bbox']}")
            else:
                lines.append("> Anomaly detected by PatchCore, but YOLO could not localize a specific defect.")
        else:
             lines.extend([
                f"## ⚠️ FINAL RESULT: {status}",
                "Pipeline encountered an issue or unknown state."
             ])
        
        lines.extend([
            "",
            "---",
            "## PatchCore Analysis (Backend)",
            ""
        ])
        
        pc = pipeline_result.get("patchcore")
        if pc:
            lines.extend([
                f"- **Prediction:** {pc.get('prediction', 'Unknown')}",
                f"- **Normalized Anomaly Score:** {pc.get('normalized_score', 0):.2f}/100",
                f"- **Model Threshold:** {pc.get('threshold', 'Unknown')}",
            ])
            heatmap = pc.get('heatmap_path')
            if heatmap:
                 lines.extend([
                     "",
                     "### Heatmap",
                     f"![Anomaly Heatmap](../../{heatmap})"
                 ])
        else:
            lines.append("- No PatchCore data available.")
            
        lines.extend([
            "",
            "---",
            f"*Generated by Industrial AI QC System v2.0*"
        ])
        
        report_path.write_text("\n".join(lines), encoding="utf-8")
        return str(report_path)


if __name__ == "__main__":
    # Test generator with dummy data
    dummy_data = {
        "status": "FAIL",
        "category": "bottle",
        "defect_classification": "broken_large",
        "confidence_score": 0.892,
        "patchcore": {
            "prediction": "Anomaly",
            "normalized_score": 85.4,
            "threshold": 3.12,
            "heatmap_path": "reports/heatmaps/bottle/bottle_broken_large_000.png"
        },
        "yolo": {
            "detections": [
                {
                    "class": "broken_large",
                    "confidence": 0.892,
                    "bbox": [10.0, 20.0, 150.0, 200.0]
                }
            ],
            "highest_confidence": 0.892,
            "detection_count": 1
        },
        "processing_time_s": 1.23
    }
    
    gen = ReportGenerator()
    path = gen.generate(dummy_data, "datasets/bottle/test/broken_large/000.png")
    print(f"Test report generated at: {path}")
